name: Build Docker
on:
  release:
    types:
      - released

jobs:
  create_docker:
    name: Create Docker Image
    uses: https://git.tainton.uk/actions/gha-workflows/.gitea/workflows/build-push-docker.yml@main
    with:
      release: ${{ gitea.event.release.name }}
    secrets:
      ACTIONS_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
      GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
