name: Release
on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * 0"

jobs:
  # test:
  #   name: Test
  #   uses: https://git.tainton.uk/repos/roboluke/.gitea/workflows/ci.yml@main
  #   with:
  #     python-version: 3.13
  #   secrets:
  #     SONAR_HOST_URL: ${{ secrets.SONARQUBE_HOST_URL }}
  #     SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
  #     SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  tag:
    name: Tag release
    uses: https://git.tainton.uk/actions/gha-workflows/.gitea/workflows/release-with-tag.yaml@main

  create_release:
    name: Create Release
    needs: tag
    uses: https://git.tainton.uk/actions/gha-workflows/.gitea/workflows/create-release-preexisting-tag.yaml@main
    with:
      tag: ${{ needs.tag.outputs.tag_name }}
      body: ${{ needs.tag.outputs.changelog }}
    secrets:
      ACTIONS_TOKEN: ${{ secrets.ACTIONS_TOKEN }}

  get_release_id:
    name: Get Release ID
    runs-on: ubuntu-latest
    needs: [tag, create_release]
    outputs:
      releaseid: ${{ steps.getid.outputs.releaseid }}
    steps:
      - name: Get Release ID
        id: getid
        run: |
          rid=$(curl -s -X 'GET' \
          -H 'accept: application/json' \
          '${{ gitea.server_url }}/api/v1/repos/${{ gitea.repository }}/releases/latest' | jq -r '.id')
          echo "releaseid=$rid" >> "$GITEA_OUTPUT"
          echo "$rid"

  build_whl:
    name: Build Wheel File
    needs: [tag, get_release_id]
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4.2.2
        with:
          ref: ${{ needs.tag.outputs.tag_name }}
      # - name: Setup Python
      #   uses: actions/setup-python@v5
      #   with:
      #     python-version: "3.13"
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: Set up Python
        run: uv python install
      - name: Update pyproject.toml
        run: ./tools/update_pyproject.sh ${{ needs.tag.outputs.tag_name }}
      - name: Install dependencies
        run: uv sync
      - name: Build wheel file
        run: uv build
      - name: Upload Release Asset
        run: |
          for file in dist/*.whl; do
            curl -s -X POST \
            -H "Authorization: token ${{ secrets.ACTIONS_TOKEN }}" \
            -H "Content-Type: multipart/form-data" \
            -F "attachment=@${{ gitea.workspace }}/$file" \
            "${{ gitea.server_url }}/api/v1/repos/${{ gitea.repository }}/releases/${{ needs.get_release_id.outputs.releaseid }}/assets"
          done
      - name: Publish to PyPI
        run: uv publish
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
      # - name: Publish to PyPI
      #   uses: pypa/gh-action-pypi-publish@release/v1
      #   with:
      #     # user: ${{ vars.PYPI_USERNAME }}
      #     user: __token__
      #     password: ${{ secrets.PYPI_API_TOKEN }}

  # publish_pypi:
  #   name: Publish to PyPI
  #   needs: build_whl
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Create dist folder
  #       run: mkdir -p dist
  #     - uses: actions/download-artifact@v4
  #       with:
  #         name: whl
  #         path: dist
  #     - name: Publish to PyPI
  #       uses: pypa/gh-action-pypi-publish@release/v1
  #       with:
  #         # user: ${{ vars.PYPI_USERNAME }}
  #         user: __token__
  #         password: ${{ secrets.PYPI_API_TOKEN }}

  create_docker:
    name: Publish Docker Images
    runs-on: ubuntu-latest
    needs: tag
    steps:
      - name: Update Docker configuration
        continue-on-error: true
        run: |
          mkdir -p /etc/default
          mkdir -p /etc/docker
          touch -a /etc/default/docker
          touch -a /etc/docker/daemon.json
          echo "DOCKER_OPTS=\"--insecure-registry ${{ vars.PACKAGES_REGISTRY_URL }}\"" >> /etc/default/docker
          echo "{\"insecure-registries\": [\"${{ vars.PACKAGES_REGISTRY_URL }}\"]}" > /etc/docker/daemon.json

      - name: Get repo name
        id: split
        run: echo "repo=${REPO##*/}" >> "$GITEA_OUTPUT"
        env:
          REPO: ${{ gitea.repository }}

      - name: Check out repository
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
          ref: ${{ needs.tag.outputs.tag_name }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Gitea Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.PACKAGES_REGISTRY_URL }}
          username: ${{ vars.ACTIONS_USERNAME }}
          password: ${{ secrets.ACTIONS_TOKEN }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ vars.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          tags: type=semver,pattern=v{{version}},value=${{ needs.tag.outputs.tag_name }}
          images: |
            ghcr.io/${{ vars.GHCR_USERNAME }}/${{ steps.split.outputs.repo }}
            ${{ vars.PACKAGES_REGISTRY_URL }}/${{ gitea.repository }}

      - name: Print metadata
        run: |
          printf "Annotations:\n${{ steps.meta.outputs.annotations }}"
          echo ""
          printf "Labels:\n${{ steps.meta.outputs.labels }}"
          echo ""
          printf "Tags:\n${{ steps.meta.outputs.tags }}"

      - name: Build images
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          load: true
          annotations: ${{ steps.meta.outputs.annotations }}
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}

      - name: Push images
        run: |
          strtags="${{ steps.meta.outputs.tags }}"
          readarray -t lines <<<"$strtags"
          for element in "${lines[@]}"; do docker push "$element"; done
          unset strtags lines
