name: Release
on:
  workflow_dispatch:
  schedule:
    - cron: "0 9 * * 0"

jobs:
  test:
    uses: https://git.tainton.uk/actions/gha-workflows/.gitea/workflows/ci-python-uv-with-docker.yml@main
    with:
      python-version: 3.13
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  create_release:
    name: Create Release
    uses: https://git.tainton.uk/actions/gha-workflows/.gitea/workflows/create-release.yml@main

  create_docker:
    name: Create Docker Image
    needs: create_release
    if: ${{ needs.create_release.outputs.success == 'true' }}
    uses: https://git.tainton.uk/actions/gha-workflows/.gitea/workflows/build-push-docker.yml@main
    with:
      release: ${{ needs.create_release.outputs.release_name }}
