name: Snyk

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "@daily"

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.2.2

      - name: Snyk
        uses: snyk/actions/python@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
