name: CI
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - "README.md"
      - "LICENSE.md"
      - ".gitignore"
      - ".github/CODEOWNERS"
      - ".github/renovate.json"
      - ".github/dependabot.yml"

jobs:
  ci:
    uses: luketainton/gha-workflows/.github/workflows/ci-python-with-docker.yml@main
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
