name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]
    paths-ignore:
      - 'README.md'
      - 'LICENSE.md'
      - '.gitignore'
      - 'CODEOWNERS'
      - 'renovate.json'

jobs:
  ci:
    uses: luketainton/gha-workflows/.github/workflows/ci-python.yml@main
    env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
