name: Build
on:
  push:
    branches: [main]

jobs:
  build:
    name: GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Login to GitHub Container Registry
        run: echo ${{ secrets.GHCR_ACCESS_TOKEN }} | docker login ghcr.io -u luketainton --password-stdin
      - name: Build image for GitHub Package Registry
        run: docker build . --file Dockerfile --tag ghcr.io/luketainton/roboluke-tasks:${{ github.sha }} --tag ghcr.io/luketainton/roboluke-tasks:latest
      - name: Push image to GitHub Package Registry
        run: |
          docker push ghcr.io/luketainton/roboluke-tasks:latest
          docker push ghcr.io/luketainton/roboluke-tasks:${{ github.sha }}
